version: "3.7"
services:
        smhapp:
         image: smh:10.0
         container_name: smhapp
         networks:
           - skynetbr1
         ports:
           - "8087:8080"
         depends_on:
            - smhdbnew
         links:
            - smhdbnew
         restart: always

        smhdbnew:
         image: mysql:5.7
         container_name: smhdbnew
         environment:
           - MYSQL_ROOT_PASSWORD=root
           - MYSQL_DATABASE=hibnatedb
         networks:
              skynetbr1:
                ipv4_address: 102.12.1.2 
         ports:
           - "3307:3306"
         volumes:
           - /ALM/docker/demo/volumes/smhdbvol:/var/lib/mysql
         restart: always

volumes:
  smhdbvol:

networks:
  skynetbr1:
        driver: bridge
        ipam:
         config:
           - subnet: 102.12.1.0/24
            
