version: "3.7"
services:
        smhapp:
         image: smh:1.0
         container_name: smhapp
         networks:
           - smhnet
         ports:
           - "8087:8080"
         depends_on:
            - smhdb
         restart: always

        smhdb:
         image: mysql:latest
         container_name: smhdb
         environment:
           - MYSQL_ROOT_PASSWORD=root
           - MYSQL_DATABASE=hibnatedb
         networks:
            - smhnet
         ports:
           - "3306:3306"
         volumes:
           - smhvol:/var/lib/mysql
         restart: always

volumes:
  smhvol:

networks:
  smhnet:
